### PR TITLE
Enable Travis CI

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/conda-forge/vtk-feedstock/issues/10
Closes https://github.com/conda-forge/vtk-feedstock/pull/34

Attempts to get macOS packages built by enabling Travis CI.

### CODE REVIEW

**Comment by Korijn** [comment]
This is a long shot, but the most recent version of ninja has the following line in its changelog:

> Use POSIX_SPAWN_USEVFORK with glibc, makes some full builds twice as fast #1182

It might do the trick?

**Comment by Korijn** [comment]
Now that ninja v1.8.2 is out, we can just retrigger the build to see if it makes any difference.

**Comment by Korijn** [comment]
More recent versions of clang (that come with more recent versions of xcode) are also known to have faster compile times. Why is conda-forge on `osx_image: xcode6.4`? It seems `osx_image: xcode9` is much more recent, and might provide faster build times through newer versions of clang.

**Comment by jakirkham** [comment]
> Why is conda-forge on `osx_image: xcode6.4`?

The reasoning is similar to why we use CentOS 6 for Linux builds. We try to build against the oldest OS that we want to support. That way we can guarantee that everything should work on that OS or any newer version. This `xcode6.4` has macOS 10.10, but includes the SDK for macOS 10.9. As conda-forge started out supporting macOS 10.9 and we haven't discussed changing the lowest version of the OS, we continue to try to do so. Admittedly at some point this will have to change this.

> ...might provide faster build times through newer versions of clang.

That's certainly something we can explore. Though the macOS version we target and the clang version used can be varied independently. We build clang in conda-forge in a package called `clangdev`. So we could try using that. We would need to require `libcxx` as well for C++ support.

**Comment by Korijn** [comment]
I'm closing this as it doesn't look like VTK will ever build within the Travis CI build time limit constraints.

**Pull request closed without merging**
