### PR TITLE
DOC:  add readme

### PR DESCRIPTION
**Pull request by christianbrodbeck**
Adding a readme as discussed in https://github.com/conda-forge/vtk-feedstock/issues/21 - let me know if I should add more.

### CODE REVIEW

**Comment by Korijn** [comment]
LGTM

**Comment by dfroger** [comment]
Maybe the file should be `README.md` instead of `readme.md`?

**Comment by kazemSafari** [comment]
Hi i'm trying to install "mayavi". So i installed all the prerequisite packages including vtk. But after type enter "pip install mayavi" into my ubuntu 16.04 shell,  i get a similar error mentioned in #21 - 
"from vtkOpenGLKitPython import *
    ModuleNotFoundError: No module named 'vtkOpenGLKitPython'"

How can i fix this error. I did not get your solution "christianbrodbeck"?

**Comment by christianbrodbeck** [comment]
@kazemSafari I think it just means something with your install is wrong, because these objects are created dynamically. The proper place to get help would probably be VTK, this here is just an automatic build for `conda-forge`.

**Pull request merged**
