### PR TITLE
Fix #157

### LINKED ISSUE #157: vtk9: wrong config-paths in cmake-setup
There are some wrong config paths in the cmake config files:

linux:
```
CMake Error in src/Mod/Fem/App/CMakeLists.txt:
  Imported target "VTK::opengl" includes non-existent path

    "/home/conda/feedstock_root/build_artifacts/vtk_1603657375561/_build_env/x86_64-conda-linux-gnu/sysroot/usr/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

osx:
```
CMake Error in src/Mod/Fem/App/CMakeLists.txt:
  Imported target "VTK::opengl" includes non-existent path

    "/Applications/Xcode_11.7.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

```

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Thanks @isuru

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
That seemed to work:
```
2021-04-02T08:52:23.1925079Z Patching 'lib/cmake/vtk-9.0/VTK-targets.cmake' in 3 places
```
This line was not in the previous builds.

It would be great if this could be merged @conda-forge/vtk 

/cc @isuruf - thanks for the tip!

**Comment by Tobias-Fischer** [comment]
Kind ping @conda-forge/vtk

**Review by grlee77 — APPROVED** [review]

**Comment by grlee77** [comment]
Thanks @Tobias-Fischer

**Pull request merged**
