### PR TITLE
Remove ParaView constraint

### PR DESCRIPTION
**Pull request by basnijholt**
Reverting https://github.com/conda-forge/vtk-feedstock/pull/84. Here https://github.com/conda-forge/paraview-feedstock/issues/27#issuecomment-492500135 @grlee77 mentions that the problem occurred because ParaView was built with the old compilers.

At the moment ParaView is up-to-date and compiled with the latest compilers.

Having this constraint _prevents people from installing FreeCAD_ (which depends on VTK) and ParaView in the same environment.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by basnijholt** [comment]
I have no preference with respect to labeling as broken. 

Would that block merging this PR?

**Comment by jakirkham** [comment]
cc @jschueller (for awareness)

**Comment by jschueller** [comment]
these will probably still stay incompatible as they separate the releases, which is understandable from a resource point of view

**Comment by basnijholt** [comment]
I have locally removed the constrained and installed VTK + ParaView, and indeed it doesn't work. I will close this.

**Pull request closed without merging**
