### PR TITLE
Update VTK to 8.1.0

### PR DESCRIPTION
**Pull request by marcelotrevisani**
Updated the vtk version to VTK 8.1.0

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
@tadeu 
Actually, the master branch is already failling in appveyor... kinda a weird...
I'm going to open an issue regarding that.
Should I merge that or it will be better to wait to fix that?

**Comment by nicoddemus** [comment]
Needs a rerender, hold on

**Comment by nicoddemus** [comment]
@conda-forge-admin, please rerender

**Comment by marcelotrevisani** [comment]
@nicoddemus Thank you! 👍

**Comment by nicoddemus** [comment]
@marcelotrevisani in the future please open PRs from branches in your fork instead of branches in the main repository: currently conda-forge will publish any successful builds from any branch in the main repository, which means for example `8.1.0` has already been published for [the other platforms](https://anaconda.org/conda-forge/vtk/files) even though we didn't merge this PR yet.

**Comment by marcelotrevisani** [comment]
@nicoddemus I didn't know that. Thanks for the advice! I will remember about that! 👍

**Comment by nicoddemus** [comment]
Sure thing! 😄

**Comment by jakirkham** [comment]
Could you actually go ahead and move this work to your fork and open a fresh PR before proceeding, @marcelotrevisani? Would like to avoid a plethora of incomplete packages getting uploaded to the channel before getting this right. Thanks.

**Comment by nicoddemus** [comment]
> Could you actually go ahead and move this work to your fork and open a fresh PR before proceeding, @marcelotrevisani? Would like to avoid a plethora of incomplete packages getting uploaded to the channel before getting this right. Thanks.

@jakirkham I suggest we let the current builds finish because I suspect Windows only failed because we needed to rerender the feedstock, so once it completes all packages will be uploaded and we will be set.

If on the other hand Windows fails for some reason again, then I agree completely, we should move this to a fresh PR to sort out the issue.

**Comment by marcelotrevisani** [comment]
Should I create another PR from my fork repository or just merge that as it is?

**Comment by jakirkham** [comment]
Let’s go ahead and merge it. My comment was more directed at further revisions of this PR, of which none are needed.

**Pull request merged**
