### PR TITLE
Upgrade to hdf5 1.8.18 in py2 branch

### PR DESCRIPTION
**Pull request by qwhelan**
See https://github.com/conda-forge/vtk-feedstock/pull/32 for more details

### CODE REVIEW

**Comment by grlee77** [comment]
Thanks

**Comment by grlee77** [comment]
looks like this one still needs a bump in the build number.

**Comment by qwhelan** [comment]
@grlee77 Fixed, should have realized a cherry pick might have that issue.

**Comment by Korijn** [comment]
LGTM!

**Pull request merged**
