### PR TITLE
add osx_arm64 support

### PR DESCRIPTION
**Pull request by matthiasdiener**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
If you add this package (or gmsh) to the list of packages in conda-forge-pinning-feedstock, then the bot will send PRs in correct order.

**Comment by matthiasdiener** [comment]
> If you add this package (or gmsh) to the list of packages in conda-forge-pinning-feedstock, then the bot will send PRs in correct order.

Where would I have to add the package? I added gmsh there some time ago (https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1391).

**Comment by isuruf** [comment]
That's for linux-arm and power. For osx-arm, https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/osx_arm64.txt

**Comment by matthiasdiener** [comment]
> That's for linux-arm and power. For osx-arm, https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/osx_arm64.txt

I see, thanks! As a side note, these automatic PRs do have the disadvantage that I can not modify them directly, right (since I'm not a package maintainer)? Many PRs will likely need manual attention due to the cross-compilation.

**Comment by isuruf** [comment]
True. You'll have to send a PR using the commits from the bot PR.

**Comment by matthiasdiener** [comment]
@conda-forge-admin restart CI

**Comment by isuruf** [comment]
There's still a few dependencies needed for vtk as seen here, https://raw.githubusercontent.com/regro/cf-graph-countyfair/master/status/armosxaddition.svg?sanitize=true

**Comment by isuruf** [comment]
@matthiasdiener, the bot will send another PR to update `libnetcdf` to 4.8.0 and after merging that this PR has to be rebased on top of that.

**Comment by matthiasdiener** [comment]
> @matthiasdiener, the bot will send another PR to update `libnetcdf` to 4.8.0 and after merging that this PR has to be rebased on top of that.

I see. My intention was to check whether fixing the libnetcdf version gets the build farther.

**Comment by isuruf** [comment]
Sure. That's fine. Thanks for doing that.

**Comment by isuruf** [comment]
@matthiasdiener, this is ready.

**Comment by matthiasdiener** [comment]
> @matthiasdiener, this is ready.

LGTM, thanks!

**Pull request merged**
