### PR TITLE
Activate xdmf on windows 

### PR DESCRIPTION
**Pull request by fbordeu**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by fbordeu** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
Three concurrent jobs here here (one merged PR two open ones) ended up causing pretty severe resource starvation across conda-forge. I'm going to have to ask to only ever run one job at a time here (especially as long as we have the duplicated hdfs5 builds). Alternatively, you could do
```diff
--- a/conda-forge.yml
+++ b/conda-forge.yml
@@ -1,5 +1,6 @@
 azure:
   free_disk_space: true
+  max_parallel: 25
   settings_linux:
     swapfile_size: 10GiB
 build_platform:
```
and rerender. Then the builds will be spread out a bit more at least.

**Comment by jakirkham** [comment]
It is worth noting there is an opportunity to consolidate some package variants in 9.4.0: https://github.com/conda-forge/vtk-feedstock/issues/343

Though that also involves getting 9.4.0 integrated: https://github.com/conda-forge/vtk-feedstock/pull/354

**Pull request merged**
