### PR TITLE
vtk is incompatible with expat 2.6

### PR DESCRIPTION
**Pull request by minrk**
expat 2.5 run_exports accepts `>=2.5,<3`, so expat 2.6 is being installed with current builds. I'll do a repodata patch PR separately.

upstream issue: https://gitlab.kitware.com/vtk/vtk/-/issues/19258

test added from https://gitlab.archlinux.org/archlinux/packaging/packages/paraview/-/issues/4#note_166231

### CODE REVIEW

**Comment by minrk** [comment]
arg, osmesa has had a major release since the last build, and it breaks with:

```
024-03-14T09:13:52.9684688Z In file included from /home/conda/feedstock_root/build_artifacts/vtk_1710405337176/work/ThirdParty/glew/vtkglew/src/glew.c:41:
2024-03-14T09:13:52.9685854Z /home/conda/feedstock_root/build_artifacts/vtk_1710405337176/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/include/GL/osmesa.h:125:1: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'OSMesaCreateContext'
2024-03-14T09:13:52.9686578Z   125 | OSMesaCreateContext( GLenum format, OSMesaContext sharelist );
2
```

This was reported upstream in https://gitlab.freedesktop.org/mesa/mesa/-/issues/10270 but appears to be fixed and doesn't appear to be supposed to affect linux builds anyhow.

I don't really understand how there's an issue because GLAPIENTRY and APIENTRY are both defined to be empty in GL/gl.h on linux.

I don't know if the right `-DAPIENTRY=` or something will fix it, or if we should just pin mesa to 23.

**Comment by minrk** [comment]
Had to pin osmesa to get builds to pass, can revert the pin in a new PR after merge.

**Comment by adrianinsaval** [comment]
alternatively we could remove expat from dependencies and comile VTK with `-DVTK_MODULE_USE_EXTERNAL_VTK_expat=OFF`, sounds like that's what they're doing in archlinux

**Comment by minrk** [comment]
Yeah, in general we shouldn't vendor dependencies on conda-forge, but that's a valid temporary workaround. We'd need to make sure to include the expat license in about.license_files.

If expat is installed and dynamically linked, this would be a problem as it would still conflict just as much with existing expat installs, but if it's statically linked that should be okay temporarily.

**Comment by minrk** [comment]
fwiw, rereading the arch issue, I think folks have been showing that the bundled expat _works_, but they [don't seem to be proposing](https://gitlab.archlinux.org/archlinux/packaging/packages/paraview/-/issues/4#note_165723) to actually do it in the package.

My inclination is to go with this pin for now, and https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5640 if we need it to avoid conflicts across conda-forge, and watch https://gitlab.kitware.com/vtk/vtk/-/issues/19258 for a patch we can backport.

Any opinion from @conda-forge/vtk ?

**Comment by traversaro** [comment]
A fix was released upstream: https://gitlab.kitware.com/vtk/vtk/-/commit/db8f9efca220c9d16a30958e179abae3379d0011 .

**Comment by traversaro** [comment]
> A fix was released upstream: https://gitlab.kitware.com/vtk/vtk/-/commit/db8f9efca220c9d16a30958e179abae3379d0011 .

At a first glance, that does not seem ABI compatible with existing releases.

**Comment by minrk** [comment]
OK, so looks like we need to keep pinning until the next vtk release?

**Comment by traversaro** [comment]
> OK, so looks like we need to keep pinning until the next vtk release?

Yes, from what I see that is the case, unless there is some way (that I do not see) to make the fix ABI compatible.

**Comment by minrk** [comment]
WDYT are the implications of that for https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5640 ? Is vtk's compatibility enough that we need to hold everyone else back on conda-forge?

**Comment by traversaro** [comment]
> WDYT are the implications of that for [conda-forge/conda-forge-pinning-feedstock#5640](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5640) ? Is vtk's compatibility enough that we need to hold everyone else back on conda-forge?
> 
> EDIT: I guess it doesn't really hold anything back, just the build-time version.

Until someone needs a specific feature available only on expat 2.6, that pin seems fine to me. In case anyone needs explicity expat 2.6, they can always override locally the pin in the recipe.

**Comment by minrk** [comment]
This PR (or something like it) needs to land before any other PRs to this repo (#324, #322) , which would result in reintroducing broken dependencies. I'll merge it as-is to unblock other things, unless there's an objection

**Comment by jakirkham** [comment]
Looks like the macOS builds are failing on `main`. Maybe we need a re-render or something?

**Pull request merged**
