### PR TITLE
Fix version number in egg-info file for Windows + Build pyi files

### LINKED ISSUE #234: Package installed with invalid version number on Windows
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I have added `pip check` in a downstream package build in https://github.com/conda-forge/bonsu-feedstock/pull/41, and [the build fails on Windows](https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_build/results?buildId=471138&view=logs&jobId=5be07ae1-d8ba-5406-47b6-8e3a3a12f825) with

```
(%PREFIX%) %SRC_DIR%>pip check 
bonsu 3.4.4 has requirement vtk>=5.4.2, but you have vtk -PKG-VERSION.
```
indicating that the package version number is not correctly set in the python package metadata.

Adding `pip check` to the package directly (#233) did not show up any issues though

### Installed packages

```shell
The following NEW packages will be INSTALLED:

    bonsu:                   3.4.4-py310hf24f00a_1         local      
    brotlipy:                0.7.0-py310he2412df_1003      conda-forge
    proj:                    8.2.1-h1cfcee9_0              conda-forge
    pthread-stubs:           0.4-hcd874cb_1001             conda-forge
    pugixml:                 1.11.4-h0e60522_0             conda-forge
    pycparser:               2.21-pyhd8ed1ab_0             conda-forge
    pyopenssl:               22.0.0-pyhd8ed1ab_0           conda-forge
    pysocks:                 1.7.1-py310h5588dad_4         conda-forge
    python:                  3.10.2-h9a09f29_4_cpython     conda-forge
    python_abi:              3.10-2_cp310                  conda-forge
    qt:                      5.12.9-h5909a2a_4             conda-forge
    requests:                2.27.1-pyhd8ed1ab_0           conda-forge
    setuptools:              60.9.3-py310h5588dad_0        conda-forge
    six:                     1.16.0-pyh6c4a22f_0           conda-forge
    sqlite:                  3.37.0-h8ffe710_0             conda-forge
    tbb:                     2021.5.0-h2d74725_0           conda-forge
    tbb-devel:               2021.5.0-h2d74725_0           conda-forge
    tk:                      8.6.12-h8ffe710_0             conda-forge
    tzdata:                  2021e-he74cb21_0              conda-forge
    ucrt:                    10.0.20348.0-h57928b3_0       conda-forge
    urllib3:                 1.26.8-pyhd8ed1ab_1           conda-forge
    utfcpp:                  3.2.1-h57928b3_0              conda-forge
    vc:                      14.2-hb210afc_6               conda-forge
    vs2015_runtime:          14.29.30037-h902a5da_6        conda-forge
    vtk:                     9.1.0-qt_py310hc43dec9_204    conda-forge
    wheel:                   0.37.1-pyhd8ed1ab_0           conda-forge
    win32_setctime:          1.1.0-pyhd8ed1ab_0            conda-forge
    win_inet_pton:           1.1.0-py310h5588dad_3         conda-forge
    wxpython:                4.1.1-py310h494077a_3         conda-forge
    xorg-libxau:             1.0.9-hcd874cb_0              conda-forge
    xorg-libxdmcp:           1.1.3-hcd874cb_0              conda-forge
    xz:                      5.2.5-h62dcd97_1              conda-forge
    zlib:                    1.2.11-h8ffe710_1013          conda-forge
    zstd:                    1.5.2-h6255e5f_0              conda-forge
```

### Environment info

```shell
ran directly on Azure, failing environments were:
* win_64_numpy1.19python3.9.____cpython
* win_64_numpy1.21python3.10.____cpython
```

### LINKED ISSUE #268: pyi files are missing from installed package on aarch64, ppc64 and osx-arm64
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

pyi files shipped with the `pip` installed `vtk` are missing from the conda-forge package:

`conda-forge`:
```
❯ find ~/miniconda/envs/vtk_test/lib/python3.9/site-packages/vtkmodules | grep pyi
~/miniconda/envs/vtk_test/lib/python3.9/site-packages/vtkmodules/generate_pyi.py
~/miniconda/envs/vtk_test/lib/python3.9/site-packages/vtkmodules/__pycache__/generate_pyi.cpython-39.pyc
(nothing more...)
```

`pip`:
```
❯ find ~/miniconda/envs/vtk_test/lib/python3.9/site-packages/vtkmodules | grep pyi
~/miniconda/envs/vtk_test/lib/python3.9/site-packages/vtkmodules/vtkIOVideo.pyi
~/miniconda/envs/vtk_test/lib/python3.9/site-packages/vtkmodules/vtkChartsCore.pyi
~/miniconda/envs/vtk_test/lib/python3.9/site-packages/vtkmodules/vtkPythonContext2D.pyi
~/miniconda/envs/vtk_test/lib/python3.9/site-packages/vtkmodules/vtkAcceleratorsVTKmFilters.pyi
...
```

### Installed packages

```shell
- vtk                               9.2.2  qt_py39h7c0bfd1_204  conda-forge
```

### PR DESCRIPTION
**Pull request by mwtoews**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Closes #234
Closes #268

### CODE REVIEW

**Comment by mwtoews** [comment]
@conda-forge-admin, please rerender

**Comment by mwtoews** [comment]
Also set `DVTK_BUILD_PYI_FILES:BOOL=ON` to fix #268

**Comment by mwtoews** [comment]
There is an error with the Windows builds:
```
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - found
-- Found Threads: TRUE  
CMake Error at Common/Core/CMakeLists.txt:362 (message):
  Failed to determine the thread implementation in use by the compiler.
```
This issue was raised upstream a year ago: https://gitlab.kitware.com/vtk/vtk/-/issues/18281

**Comment by Tobias-Fischer** [comment]
Can we simply patch the relevant cmake part in vtk and set 
set(CMAKE_USE_PTHREADS_INIT 0)
set(CMAKE_USE_WIN32_THREADS_INIT 1)
as described in the issue?

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin please restart ci

**Comment by Tobias-Fischer** [comment]
The problem seems to be that the `pthreads-win32` is being installed in these builds, whereas it was not installed in previous builds. Now I assume there are multiple thread implementations and cmake is getting confused.

**Comment by Tobias-Fischer** [comment]
Hmm I'm not sure what's going on when cross-compiling:
```
2023-01-03T04:35:37.4141709Z [2928/9487] : && $BUILD_PREFIX/bin/aarch64-conda-linux-gnu-c++ -fPIC -fvisibility-inlines-hidden -fmessage-length=0 -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/vtk-9.2.2 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix  -O3 -DNDEBUG  -Wl,-lc  -Wl,-lc -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--allow-shlib-undefined -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib -shared  -o lib/python3.9/site-packages/vtkmodules/vtkCommonCore.so CMakeFiles/vtkCommonCorePython.dir/CMakeFiles/vtkCommonCorePython/vtkABIPython.cxx.o CMakeFiles/vtkCommonCorePython.dir/CMakeFiles/vtkCommonCorePython/vtkArrayIteratorIncludesPython.cxx.o 
...
023-01-03T05:13:00.7198723Z cd $SRC_DIR/build/lib/python3.9/site-packages && $PREFIX/bin/python -m vtkmodules.generate_pyi -p vtkmodules -o $SRC_DIR/build/lib/python3.9/site-packages/vtkmodules vtkCommonCore vtkWebCore vtkCommonMath vtkCommonTransforms vtkCommonDataModel vtkCommonExecutionModel vtkIOCore vtkImagingCore vtkIOImage vtkIOXMLParser vtkIOXML vtkCommonMisc vtkFiltersCore vtkRenderingCore vtkRenderingContext2D vtkRenderingFreeType vtkRenderingSceneGraph vtkRenderingVtkJS vtkIOExport vtkWebGLExporter vtkInteractionStyle vtkFiltersGeneral vtkFiltersSources vtkInteractionWidgets vtkViewsCore vtkViewsInfovis vtkCommonColor vtkViewsContext2D vtkTestingRendering vtkRenderingLabel vtkRenderingQt vtkPythonContext2D vtkImagingMath vtkRenderingHyperTreeGrid vtkRenderingUI vtkRenderingOpenGL2 vtkRenderingVolume vtkRenderingVolumeOpenGL2 vtkRenderingMatplotlib vtkRenderingLOD vtkRenderingLICOpenGL2 vtkRenderingImage vtkRenderingContextOpenGL2 vtkIOLegacy vtkIOXdmf2 vtkIOVeraOut vtkIOTecplotTable vtkIOSegY vtkIOXdmf3 vtkIOParallelXML vtkIOPLY vtkIOMovie vtkIOOggTheora vtkIONetCDF vtkIOMotionFX vtkIOGeometry vtkIOParallel vtkIOMINC vtkIOLSDyna vtkIOInfovis vtkIOImport vtkParallelCore vtkIOIOSS vtkIOVideo vtkIOFFMPEG vtkIOExportPDF vtkRenderingGL2PSOpenGL2 vtkIOExportGL2PS vtkIOExodus vtkIOEnSight vtkIOCityGML vtkIOChemistry vtkIOCesium3DTiles vtkIOCONVERGECFD vtkIOHDF vtkIOCGNSReader vtkIOAsynchronous vtkIOAMR vtkInteractionImage vtkImagingStencil vtkImagingStatistics vtkImagingGeneral vtkImagingMorphological vtkImagingFourier vtkIOSQL vtkImagingSources vtkInfovisCore vtkGeovisCore vtkInfovisLayout vtkRenderingAnnotation vtkImagingHybrid vtkImagingColor vtkFiltersTopology vtkFiltersSelection vtkFiltersSMP vtkFiltersPython vtkFiltersProgrammable vtkFiltersModeling vtkFiltersPoints vtkFiltersVerdict vtkFiltersStatistics vtkFiltersImaging vtkFiltersExtraction vtkFiltersGeometry vtkFiltersHybrid vtkFiltersTexture vtkFiltersParallel vtkFiltersParallelImaging vtkCommonSystem vtkFiltersParallelDIY2 vtkFiltersGeneric vtkCommonComputationalGeometry vtkFiltersFlowPaths vtkFiltersAMR vtkDomainsChemistry vtkDomainsChemistryOpenGL2 vtkFiltersHyperTree vtkCommonPython vtkChartsCore
2023-01-03T05:13:00.7203661Z Traceback (most recent call last):
2023-01-03T05:13:00.7204199Z   File "$BUILD_PREFIX/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2023-01-03T05:13:00.7204985Z     return _run_code(code, main_globals, None,
2023-01-03T05:13:00.7205399Z   File "$BUILD_PREFIX/lib/python3.9/runpy.py", line 87, in _run_code
2023-01-03T05:13:00.7205777Z     exec(code, run_globals)
2023-01-03T05:13:00.7206327Z   File "$SRC_DIR/build/lib/python3.9/site-packages/vtkmodules/generate_pyi.py", line 37, in <module>
2023-01-03T05:13:00.7206840Z     from vtkmodules.vtkCommonCore import vtkObject, vtkSOADataArrayTemplate
2023-01-03T05:13:00.7207519Z ImportError: $SRC_DIR/build/lib/python3.9/site-packages/vtkmodules/vtkCommonCore.so: cannot open shared object file: No such file or directory

```

**Comment by Tobias-Fischer** [comment]
Hi @mwtoews @conda-forge/vtk - would you be happy with this PR in the current state? Importantly, besides fixing #234 and partly addressing #268 (only for native builds), it fixes the Windows builds that are currently blocking PRs #272 and #273

**Comment by mwtoews** [comment]
Thanks for fixing the more difficult aspects @Tobias-Fischer I haven't checked the build logs, but the CI pass looks good to me.

**Pull request merged**
