### PR TITLE
Enable VTK_GUISupportQt and VTK_RenderingSupportQt for windows

### PR DESCRIPTION
**Pull request by JDuffeyBQ**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fixes https://github.com/conda-forge/vtk-feedstock/issues/255

These changes were adapted for batch script from the code in `build-base.sh`.

### CODE REVIEW

**Comment by JDuffeyBQ** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
This has been here for a little while, apologies. Could you please add a test that makes sure the support is actually enabled? Happy to merge after.

**Comment by JDuffeyBQ** [comment]
Yes no problem I'll get the test in.

**Review by Tobias-Fischer — APPROVED** [review]

**Comment by Tobias-Fischer** [comment]
Lgtm - @conda-forge/vtk please let us know if there are objections

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin  please rerender

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin please rerender

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin please rerender

**Pull request merged**
