### PR TITLE
9.1.0 h39d90e

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
I think this is ready to go. Please double-check the addition of `DVTK_REQUIRE_LARGE_FILE_SUPPORT_EXITCODE` - I think it should be set to `0` but I'm not 100% sure.

**Comment by grlee77** [comment]
Thanks for getting this working!

> DVTK_REQUIRE_LARGE_FILE_SUPPORT_EXITCODE - I think it should be set to 0 but I'm not 100% sure.

don't know the answer to this. will leave it open for a bit to see if there is other feedback...

**Comment by Tobias-Fischer** [comment]
@traversaro - can you provide any insights? You're my cmake go-to person :)

**Comment by traversaro** [comment]
> 
> 
> @traversaro - can you provide any insights? You're my cmake go-to person :)

I looked for references to the `VTK_REQUIRE_LARGE_FILE_SUPPORT_EXITCODE` CMake option in VTK's code and documentation, but I could not find anything. Do you have any reference?

**Comment by Tobias-Fischer** [comment]
No .. it showed up in the build log, but no other references ..

**Comment by traversaro** [comment]
For some reason I can't access past Windows build log with error:
not_expected_error

**Comment by Tobias-Fischer** [comment]
It basically said sth like "Cannot execute bla bla, when cross compiling you need to set DVTK_REQUIRE_LARGE_FILE_SUPPORT_EXITCODE manually".

**Comment by traversaro** [comment]
> 
> 
> It basically said sth like "Cannot execute bla bla, when cross compiling you need to set DVTK_REQUIRE_LARGE_FILE_SUPPORT_EXITCODE manually".

Ah! This sounds like a call to [`try_run`](https://cmake.org/cmake/help/latest/command/try_run.html). I will check for it.

**Comment by Tobias-Fischer** [comment]
Yes that must be it!

**Comment by traversaro** [comment]
Related code:
* https://github.com/Kitware/VTK/blob/v9.1.0/CMakeLists.txt#L98
* https://github.com/Kitware/VTK/blob/v9.1.0/CMake/vtkRequireLargeFilesSupport.cxx

**Comment by Tobias-Fischer** [comment]
So it seems like this is checking for support for 64 bit filesystems, which have been around for quite some time now. Returning `0` is correct in that case. So I think all good!

**Comment by traversaro** [comment]
> 
> 
> So it seems like this is checking for support for 64 bit filesystems, which have been around for quite some time now. Returning `0` is correct in that case. So I think all good!

Yes, it seems correct indeed!

**Pull request merged**
