### PR TITLE
Use netcdf-cxx4

### PR DESCRIPTION
**Pull request by jakirkham**
Related to issue ( https://github.com/conda-forge/vtk-feedstock/issues/55 ). Adds `netcdf-cxx4` as a dependency.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by jakirkham** [comment]
Current blocker are...

* There are no Windows packages ( https://github.com/conda-forge/netcdf-cxx4-feedstock/issues/20 )
* Unix platforms fail to detect it (or I'm missing something).

```
-- Failed to find NetCDF interface for CXX
CMake Error at /Users/distiller/miniconda3/conda-bld/vtk_1526281488411/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find NetCDF (missing: NETCDF_HAS_INTERFACES)
Call Stack (most recent call first):
  /Users/distiller/miniconda3/conda-bld/vtk_1526281488411/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  CMake/FindNetCDF.cmake:118 (find_package_handle_standard_args)
  CMake/vtkModuleMacros.cmake:950 (find_package)
  ThirdParty/netcdfcpp/CMakeLists.txt:1 (vtk_module_third_party)
```

ref: https://circleci.com/workflow-run/255bce21-66ed-43c4-a593-7a382d8e2f1f

**Comment by jakirkham** [comment]
@demarle, any idea why VTK doesn't pick up on the NetCDF C++ interface? Is there some way we can "coax" it to use the `conda` package instead?

**Comment by grlee77** [comment]
I think the problem is the issue raised here:

https://gitlab.kitware.com/vtk/vtk/issues/17305

**Comment by demarle** [comment]
See also: https://gitlab.kitware.com/paraview/paraview/issues/18306

**Comment by xylar** [comment]
Can this be closed?  The issue may not have been addressed yet but the solution will need to be re-assessed with 9.0.0 and probably would need a different solution in the current version (8.2.0).

**Comment by xylar** [comment]
Closing this because I think it isn't relevant anymore.

**Pull request closed without merging**
