### PR TITLE
Rebuild for proj 7.0.0

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@conda-forge/core, any idea why VTK didn't get an automatic PR for proj 7.0.0 migration?

**Comment by isuruf** [comment]
@conda-forge/bot is the team you should ping.

**Comment by xylar** [comment]
Oh, sorry, I see.  It's only a dependency in the dev version, not here.

**Comment by xylar** [comment]
Okay, thanks @isuruf.  But it's my mistake.

**Pull request closed without merging**
