### PR TITLE
Update recipe to VTK 7.1.1

### PR DESCRIPTION
**Pull request by tadeu**

### CODE REVIEW

**Comment by Korijn** [comment]
LGTM!

**Comment by grlee77** [comment]
Looks good.   It's always nice to be able to remove a patch.

Can you also make an equivalent PR for the `py2` branch as well?  (We had to move the Python 2.7 build to a separate branch to get around build time limitations.)

**Comment by tadeu** [comment]
@grlee77, sure!

**Comment by grlee77** [comment]
Great.  Thanks!

**Pull request merged**
