### PR TITLE
update tbb + rerender

### PR DESCRIPTION
**Pull request by looooo**
please stop the builds if there are obvious problems with the update.

### CODE REVIEW

**Comment by looooo** [comment]
seems to look good so far. @jakirkham any ideas of other things which should be included in this PR? Is it possible to remove the hdf5 pinning?

**Comment by looooo** [comment]
- [ ] build-number needs to be updated!

**Comment by looooo** [comment]
Thanks @marcelotrevisani. It would be nice if someone can merge this.

**Comment by marcelotrevisani** [comment]
I think that should be good to go
Thanks! :tada:

**Pull request merged**
