### PR TITLE
Add tbb support

### PR DESCRIPTION
**Pull request by marcelotrevisani**
Added TBB support for VTK

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
@Korijn , could you please review that for me?

**Comment by jakirkham** [comment]
FYI will need a build number bump as well.

**Comment by Korijn** [comment]
There might be a `DVTK_USE_SYSTEM_TBB` you also need to enable? I'm not entirely sure.

Otherwise, looks good to me!

**Comment by marcelotrevisani** [comment]
@Korijn I think it's not necessary at all. If you see the options passed as a parameter to the Kitware CI such as:
https://open.cdash.org/buildSummary.php?buildid=5102452

You will see something like:
"/opt/cmake/bin/cmake" "--no-warn-unused-cli" "-DCTEST_USE_LAUNCHERS:BOOL=1" "-DVTK_RENDERING_BACKEND:STRING=OpenGL2" "-DVTK_USE_SYSTEM_LIBRARIES:BOOL=OFF" "-DModule_vtkAcceleratorsVTKm:BOOL=ON" "-DVTK_PYTHON_VERSION:STRING=2" "-DVTK_WRAP_PYTHON:BOOL=ON" "-DVTK_QT_VERSION:STRING=5" "-DVTK_LINKER_FATAL_WARNINGS:BOOL=ON" "-DVTK_Group_Web:BOOL=ON" "-DQt5_DIR:PATH=/opt/Qt/5.9.2/gcc_64/lib/cmake/Qt5" "-DCMAKE_BUILD_TYPE:STRING=Release" "-DVTK_DATA_STORE:PATH=/home/kitware/Dashboards/ExternalData" "-DBUILD_EXAMPLES:BOOL=ON" "-DVTK_BUILD_ALL_MODULES_FOR_TESTS:BOOL=ON" "-DVTK_Group_Qt:STRING=ON" "-DBUILD_SHARED_LIBS:BOOL=ON" "-DVTKm_ENABLE_CUDA:BOOL=ON" "-DVTKm_CUDA_Architecture:STRING=native" "-DModule_vtkPythonInterpreter:BOOL=ON" "-DBUILD_TESTING:BOOL=ON" "-DVTK_Group_MPI:BOOL=ON" "-DVTK_DEFAULT_RENDER_WINDOW_OFFSCREEN:BOOL=ON" "-DVTK_USE_LARGE_DATA:BOOL=ON" "-DVTK_LEGACY_REMOVE:BOOL=ON" "-DVTK_WRAP_JAVA:BOOL=OFF" "-**DVTK_SMP_IMPLEMENTATION_TYPE:STRING=TBB**" "-DVTK_DEBUG_LEAKS:BOOL=ON" "-DVTK_ENABLE_KITS:BOOL=OFF" "-DCTEST_USE_LAUNCHERS:BOOL=TRUE" "-GNinja" "/home/kitware/buildslave/root/vtk-adora-linux-shared-release_gcc_mpi_python_qt_tbb_vtkm/source"

**Comment by marcelotrevisani** [comment]
@jakirkham Sure, my mistake!

**Comment by marcelotrevisani** [comment]
@jakirkham @Korijn , I don't know why, but I push the modifications regarding the build number but it's not appearing here, so I will close this PR and create another one with this modifications, ok?

**Comment by jakirkham** [comment]
It's probably GitHub being slow.

ref: https://mobile.twitter.com/githubstatus/status/920321606060249088

**Pull request closed without merging**
