### PR TITLE
Enable vtkFiltersParallelDIY2

### PR DESCRIPTION
**Pull request by whophil**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Attempt to address #250

### CODE REVIEW

**Comment by whophil** [comment]
Oddly, I didn't add any flags to the Windows build, yet that build has no complaints when importing `vtk.vtkFiltersParallelDIY2`. I guess the Windows build has this module enabled by default?

**Comment by whophil** [comment]
This is ready for review, but seems like it should go in after #251

**Comment by whophil** [comment]
@conda-forge-admin, please rerender

**Comment by whophil** [comment]
Now rebased after merge of #251, also bumped build version

**Review by basnijholt — APPROVED** [review]

**Pull request merged**
