### PR TITLE
Rebuild for proj821 manually

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Fix for #229 - looking good so far. 

/Cc @wolfv - need it for the rebuild

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Fixes #229 #228 

I suggest to stick with cos6 for now, as I am not sure what the issue with the cos7-libEGL is (lots of linker errors to wayland stuff). It would be great if we could get the proj and jsoncpp migrations in with this PR and not being blocked by a seperate issue that hasn't actually anything to do with the migrations. If it's okay with @conda-forge/vtk I'll open a separate issue on this to keep track of it.

**Comment by Tobias-Fischer** [comment]
Hi @conda-forge/vtk - this is ready to be merged. Thanks :).

/cc @wolfv

**Review by basnijholt — APPROVED** [review]
Thanks for fixing this!

LGTM. I'll merge tomorrow if there are no objections.

**Pull request merged**
