### PR TITLE
Fix segfault during Mayavi installation

### LINKED ISSUE #13: segfault
VTK is installed with:

    conda create -n vtk -c conda-forge vtk=7.0.0 python=3.5
    source activate vtk

This segfaults:

    import vtk
    obj = vtk.vtkRenderingLICPython.vtkLineIntegralConvolution2D()
    obj.GetCommunicator()

### PR DESCRIPTION
**Pull request by dfroger**
Fixes #13

### CODE REVIEW

**Comment by grlee77** [comment]
LGTM assuming the CI passes.  Thanks for getting to the bottom of this!

**Comment by dfroger** [comment]
It does no find the patch, will look at it tomorrow

**Comment by Cadair** [comment]
Has there been any progress on this? It looks as though VTK 7.1.1 is not very far away which would fix it upstream?

**Comment by Korijn** [comment]
I think you answered your own question

**Comment by Cadair** [comment]
haha, I suppose my question was, is this PR likely to get merged before 7.1.1 is released?

**Comment by Korijn** [comment]
Hmm... for some reason CI status doesn't include travis and circle... would be good to know that they also pass before we merge this.

**Comment by dfroger** [comment]
closing and reopening the PR shoud trigger CI again

**Comment by dfroger** [comment]
We don't have travis, but that's ok, as the build is skipped on osx.

**Comment by dfroger** [comment]
appveyor build was not started, I just clicked "re-build" pr in appveyor UI. PY=2.7 builds are currently running, PY=3.4 and PY=3.5 are queued.

**Comment by dfroger** [comment]
PY=3.4 is building. Everything should be green soon...

**Comment by Korijn** [comment]
LGTM!

**Comment by dfroger** [comment]
Seems that build number should be 2 instead of 1?

**Comment by dfroger** [comment]
In the meantime, another merged PR did increase the build number to 1. So this PR didn't actually increase the bulid number (as it increase the old build number from 0 to 1...). I see it too late...

**Comment by Korijn** [comment]
open a new one?

**Pull request merged**
