### PR TITLE
[NO MRG] cb3 update

### PR DESCRIPTION
**Pull request by isuruf**
@msarahan, do you know why the matrix for `vtk_with_osmesa` doesn't work?

### CODE REVIEW

**Comment by msarahan** [comment]
I think, but have not completely confirmed, that the issue is that your yaml file is not being automatically converted to boolean values correctly.  I think they're coming out as simply strings, in which case "True" and "False" are both True in the boolean sense.  I find that behavior unintuitive, and will look into a fix.

**Comment by msarahan** [comment]
That was an issue, but not the only one.  The real issue was that selectors were being applied prior to detecting used variables, and thus were not being looped over.  I'll fix that in the next bugfix release.

**Comment by isuruf** [comment]
Thanks for looking into this. Is there some change we have to do in conda-smithy?

**Comment by msarahan** [comment]
I don't think any change to conda-smithy will be necessary.  Purely an implementation detail in conda-build.

**Comment by marcelotrevisani** [comment]
Can we close this merge request? Because I think it was already fixed with the #51 

@isuruf

**Comment by jakirkham** [comment]
There are some contents that should be pulled from this into probably a fresh PR as they are needed for `conda-build` 3 support. Also suspect some new features that @isuruf added may help address issue ( https://github.com/conda-forge/vtk-feedstock/issues/47 ). If you have time to take this on, would encourage you to do so.

**Comment by jakirkham** [comment]
Now that PR ( https://github.com/conda-forge/vtk-feedstock/pull/54 ) is merged are we good to close this or were there other things we should be including from it?

**Pull request closed without merging**
