### PR TITLE
Generate an egg-info file and test the pkg_resources finds it

### PR DESCRIPTION
**Pull request by mwcraig**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)

This PR is intended to fix the issue described in https://github.com/enthought/mayavi/issues/652, which occurs because because the conda-forge vtk currently doesn't produce anything that `pkg_resources` can find.

### CODE REVIEW

**Comment by christianbrodbeck** [comment]
Looks like it needs `setuptools` added as dependency

```
===== testing package: vtk-8.1.1-py36hdceb404_202 =====
running run_test.py
Traceback (most recent call last):
  File "/Users/distiller/miniconda3/conda-bld/vtk_1531645356383/test_tmp/run_test.py", line 5, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
Tests failed for vtk-8.1.1-py36hdceb404_202.tar.bz2 - moving package to /Users/distiller/miniconda3/conda-bld/broken
WARNING:conda_build.build:Tests failed for vtk-8.1.1-py36hdceb404_202.tar.bz2 - moving package to /Users/distiller/miniconda3/conda-bld/broken
removing: vtk-8.1.1-py36hdceb404_202.tar.bz2
TESTS FAILED: vtk-8.1.1-py36hdceb404_202.tar.bz2
Exited with code 1
```

**Comment by mwcraig** [comment]
Thanks @christianbrodbeck!

**Comment by jakirkham** [comment]
Would it make sense to upstream this change?

cc @demarle

**Comment by mwcraig** [comment]
Any object to merging this, @jakirkham? I don't object at all to it going upstream but would like to get vtk working with mayavi

**Comment by msarahan** [comment]
I would argue that this should not be upstreamed.  vtk as a pip package has an equivalent of this, and that's what mayavi is expecting.  The wheels are built completely differently.  Because we build vtk as a traditional library, we must add this for usage with things that think it's a python package.  This is really a packaging thing, and does not belong in vtk proper.

CC @jcfr, who I discussed this with at SciPy.

**Comment by jcfr** [comment]
:+1: 

May be worth adding a comment in the build script indicating that this is required to support package making use of `__requires__` (e.g mayavi). See https://setuptools.readthedocs.io/en/latest/pkg_resources.html#workingset-objects

**Comment by jcfr** [comment]
:+1:

**Comment by Cadair** [comment]
can this now be merged? :)

**Comment by mwcraig** [comment]
Just did it...

**Comment by mwcraig** [comment]
oops; should have thought about that....

**Comment by grlee77** [comment]
Unless I am mistaken, builds didn't show up at https://anaconda.org/conda-forge/vtk/files because both this PR and the recently merged #63 bumped the build number to 2.  I guess we will need a new PR to bump the build number and rebuild...

**Comment by jakirkham** [comment]
Ouch! Yep, you're right. [This]( https://github.com/conda-forge/vtk-feedstock/blame/112ffb86e189335f0ac0b4132a18b9dab58a6de9/recipe/meta.yaml#L2 ) elucidates it.

**Comment by mwcraig** [comment]
:facepalm: -- @jakirkham do you want the honors of opening the PR to bump the build number or shall I? I *think* we could open that PR and merge before waiting for CI to complete since all we are doing is bumping the build number and we already know the build passes. Agree?

**Comment by grlee77** [comment]
> we could open that PR and merge before waiting for CI to complete

yeah, I think you could do that. (potentially waiting to make the PR until the evening/night to reduce the CI load during business hours)

**Pull request merged**
