### PR TITLE
Fix VTK::opengl linking on OSX

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Currently downstream packages fail to link to vtk::opengl, as can be seen in https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=311003&view=logs&jobId=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&j=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&t=933f325c-924e-533d-4d95-e93b5843ce8b
```
CMake Error in tools/CMakeLists.txt:
  Imported target "VTK::opengl" includes non-existent path

    "/Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework"

  in its INTERFACE_INCLUDE_DIRECTORIES.
```

This PR includes a patch (kudos to @traversaro) to remove OPENGL_INCLUDE_DIR from the exported include directories, as it is not relocatable. I have tested it locally and it solves the compile issues with PCL on OSX.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
This PR is ready to be merged @conda-forge/vtk

The main change is adding this to the conda_build_config:
```
    - tag: 'CMake build metadata OSX'
      glob_patterns:
        - '*.cmake'
      regex_re: '([^;\s"]+/MacOSX\d*\.?\d*\.sdk)'
      replacement_re: '$ENV{CONDA_BUILD_SYSROOT}'
```

There is already a similar patch in place for Linux:
```
    - tag: 'CMake build metadata'
      glob_patterns:
        - '*.cmake'
      regex_re: '([^;\s"]+/sysroot)'
      replacement_re: '$ENV{CONDA_BUILD_SYSROOT}'
```

I have locally tested building PCL after applying this PR, and it solves the current problem.

**Comment by Tobias-Fischer** [comment]
Ping @conda-forge/vtk - it would be great if someone could have a look at this PR :)

**Comment by grlee77** [comment]
I am not familiar with those type of regex replacements in recipes, but the addition seems consistent with the existing Linux case and it seems you have already verified that it works, so I will go ahead and merge

**Comment by Tobias-Fischer** [comment]
Thanks @grlee77

**Pull request merged**
