### PR TITLE
MNT: rerender

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #106.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

### CODE REVIEW

**Comment by xylar** [comment]
@looooo, do you have a suggested test we could add to make sure #106 is actually fixed?

**Comment by looooo** [comment]
@xylar I guess we should check if all paths to host-env are replaced correctly. But maybe a more central feedstock should be used to do these tests as multiple feedstocks are dependent on correct path-replacement.

**Comment by xylar** [comment]
@looooo, I guess I meant a vtk-specific test that would show that this had not happened.  Something that similar to what you ran that revealed the problem.

**Comment by xylar** [comment]
Let's not worry about that for now.  We can add it later if you think of something useful.

**Pull request merged**
