### PR TITLE
Update recipe to VTK 7.1.0

### PR DESCRIPTION
**Pull request by dfroger**

### CODE REVIEW

**Comment by Korijn** [comment]
I think you need to make sure you have the latest `conda-smithy` package installed, and then call `conda-smithy rerender` on the repository.

**Comment by dfroger** [comment]
@Korijn thanks done!

**Comment by ivoflipse** [comment]
LGTM!

**Comment by Korijn** [comment]
Just need to add your username to `recipe-maintainers` in the recipe file!

**Comment by Korijn** [comment]
When CI passes again (I add your name to the maintainers list), we can merge this.

**Comment by dfroger** [comment]
@Korijn thank for adding me in the maintainers list

**Pull request merged**
