### PR TITLE
add support for tkinter rendering

### PR DESCRIPTION
**Pull request by jsbronder**
It's convenient to be able to use tkinter for quickly mocking up a UI as
it's part of the python stdlib and has no other dependencies.

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
Would add `tk` explicitly as a dependency.

@conda-forge/vtk, thoughts?

**Comment by ivoflipse** [comment]
Is there a flavor of Python without it? But still good to be explicit

**Comment by jsbronder** [comment]
Anything I can do to move this along?

**Comment by xylar** [comment]
Yes, I believe the request was to add `tk` as a dependency.  I'm not sure if that's just at runtime or also at build.

**Comment by xylar** [comment]
Also, since #104 was also build 9, you'll need to bump the build number again.  Might be worth rebasing onto the new `master`.

**Comment by xylar** [comment]
Thanks @jsbronder.  I'll set this to merge as soon as CI passes.  Do you happen to know if the flag for enabling TK will be the same for 9.0.0?  I'll make sure to add this to #105 either way.

**Comment by xylar** [comment]
I just noticed that `tk` support isn't enabled in the Windows build.  Do we want to add that, too, for consistency?

**Comment by xylar** [comment]
@jsbronder, I went ahead and added TK under Windows, too.  Hope you don't mind.

**Comment by jsbronder** [comment]
Ah sorry about that.  This is my first PR to anything on conda-forge and I didn't realize I needed to edit the batch file.

**Comment by xylar** [comment]
No worries.  Welcome to `conda-forge`!  Some maintainers are more responsive than others.  As you've learned, doesn't hurt to ping them if no one responds for awhile.

**Comment by jsbronder** [comment]
Looks like it's still the same option (and not buried under the third party libs now), https://gitlab.kitware.com/vtk/vtk/-/blob/master/CMakeLists.txt#L157

**Comment by xylar** [comment]
Great, I just rebased #105 onto this branch so we should be good to go (assuming CI passes in 2 hours or whatever...).

**Pull request merged**
