### PR TITLE
Create 9.0.1 with EGL and OSMesa on branch

### PR DESCRIPTION
**Pull request by basnijholt**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

I have put a lot of work into getting VTK with EGL and VTK in https://github.com/conda-forge/vtk-feedstock/pull/225.

Unfortunately, I need to be able to simultaneously install FreeCAD and VTK with EGL but because FreeCAD is only built with VTK 9.0.1 and conflicts prevent me from updating FreeCAD to support 9.1.0, see https://conda-forge.org/status/#other_migrations.

This is because SMESH does **not support** OCCT 7.6 and OCCT 7.5 is only built with VTK 9.0.1.

Therefore, I have created a branch `9.0.1` from master where this PR will be merged into.

### CODE REVIEW

**Comment by basnijholt** [comment]
@matthiasdiener any objections?

**Comment by matthiasdiener** [comment]
> @matthiasdiener any objections?

No objections from me (although I'm not familiar with this way of building an older version of a package).

**Comment by basnijholt** [comment]
This is the way to maintain older versions https://conda-forge.org/docs/maintainer/updating_pkgs.html?highlight=branch#maintaining-several-versions

Otherwise, it's nothing special.

Think we can merge this?

**Comment by matthiasdiener** [comment]
> https://conda-forge.org/docs/maintainer/updating_pkgs.html?highlight=branch#maintaining-several-versions

I see, thanks. I guess it's fine to merge this.

**Comment by Tobias-Fischer** [comment]
@basnijholt - do you want to add that branch to the ABI migration branches?

**Comment by basnijholt** [comment]
That might be nice but I'm AFK until February.

**Pull request merged**
