### PR TITLE
Attempt to reenable osmesa build

### PR DESCRIPTION
**Pull request by Cadair**
I would like to see osmesa working in full headless mode, so I guess this is the first place to start.

### CODE REVIEW

**Comment by grlee77** [comment]
@conda-forge-admin, please rerender

**Comment by Cadair** [comment]
oh that went well :see_no_evil:

**Comment by gdevenyi** [comment]
Whats the last version with working osmesa?

**Comment by matthiasdiener** [comment]
@conda-forge-admin, rerender

**Comment by matthiasdiener** [comment]
Done in #225.

**Pull request closed without merging**
