### PR TITLE
MNT: Re-rendered with conda-smithy 2.0.1

### PR DESCRIPTION
**Pull request by dfroger**

### CODE REVIEW

**Comment by dfroger** [comment]
Time out for the Linux build (at 7829/7842). No windows build?

**Comment by dfroger** [comment]
On CircleCI I tried to modify parallelism from `1x out of 4x` to `4x out of 4x`.

**Comment by Korijn** [comment]
> Time out for the Linux build (at 7829/7842). 

We disabled the linux build for py34, so that py27 and py35 could complete within the timeout. Now that py36 is added to the build matrix, we're back to time out issues. We already optimized quite heavily by using `ninja` which is by far the fastest compiler toolchain for VTK. So I'm not sure what to do here.

Isn't it hilarious that the windows build completes all configurations in under 30 minutes though? :)

> No windows build?

AppVeyor doesn't show up sometimes for PRs... not sure why. It should!

**Comment by jakirkham** [comment]
> On CircleCI I tried to modify parallelism from `1x out of 4x` to `4x out of 4x`.

Please revert that. This does nothing, but run all of the builds 4 times. It also blocks any other jobs from running on CircleCI in the interim.

**Comment by dfroger** [comment]
@jakirkham reverted

**Comment by jakirkham** [comment]
Thanks @dfroger.

**Pull request closed without merging**
